import type { SessionPackV2 } from "../../../lib/types/session-pack";

export const MOCK_COACH_LITE_SESSION_PACK: SessionPackV2 = {
  sessionPackId: "preview-pack-u12-defending-001",
  specVersion: "session-pack.v2",
  title: "U12 Defending and Transition Session",
  sport: "soccer",
  ageGroup: "U12",
  level: "club",
  durationMinutes: 75,
  equipment: ["16 cones", "10 balls", "12 bibs", "2 mini goals", "1 full goal"],
  space: {
    surfaceType: "grass",
    areaType: "half-field",
    sizeLabel: "half field",
  },
  intensity: "medium",
  objective:
    "Help players recognize pressing cues, recover shape quickly, and transition forward after a regain.",
  activities: [
    {
      activityId: "act_001",
      name: "Arrival Ball Mastery and Movement Prep",
      phase: "warm-up",
      minutes: 12,
      objective: "Prepare players physically while reinforcing scanning and close control.",
      setup:
        "Create a 20x20 yard square with cones. Each player starts with a ball inside the area.",
      instructions:
        "Players move freely with the ball, changing direction on the coach's signal and performing a short acceleration into space.",
      organization: "Split the group evenly across the square and rotate demonstration players every minute.",
      coachingPoints: [
        "keep the ball close when changing direction",
        "scan before accelerating",
        "land balanced before the next action",
      ],
      regressions: ["reduce the movement speed before each acceleration"],
      progressions: ["add a passive chaser after each signal"],
      equipment: ["12 cones", "10 balls"],
      space: {
        areaType: "grid",
        sizeLabel: "20x20 yards",
      },
    },
    {
      activityId: "act_002",
      name: "4v2 Defensive Rondo",
      phase: "technical",
      minutes: 18,
      objective: "Improve pressing angle, cover, and communication between the two defenders.",
      setup:
        "Mark a 20x20 yard grid with four cones. Place four attackers on the outside and two defenders inside with one ball in play.",
      instructions:
        "Outside players keep possession with quick support angles while the two defenders work together to press and cover.",
      organization: "Rotate defenders every 60 to 90 seconds so all players repeat the defending roles.",
      coachingPoints: [
        "close space together, not alone",
        "force play toward a predictable side",
        "cover the line behind the pressing defender",
      ],
      progressions: ["limit the attackers to two touches"],
      regressions: ["increase the grid size slightly"],
      commonMistakes: [
        "both defenders jumping to the same pass",
        "defenders arriving square instead of angled",
      ],
      equipment: ["4 cones", "1 ball", "6 bibs"],
      space: {
        areaType: "grid",
        sizeLabel: "20x20 yards",
      },
      constraints: ["use one active ball only"],
      diagrams: [
        {
          diagramId: "diag_001",
          specVersion: "drill-diagram-spec.v1",
          diagramType: "setup",
          title: "4v2 Defensive Rondo Setup",
          spec: {
            diagramId: "diag_001",
            specVersion: "drill-diagram-spec.v1",
            activityId: "act_002",
            title: "4v2 Defensive Rondo Setup",
            diagramType: "setup",
            sport: "soccer",
            canvas: {
              width: 1200,
              height: 800,
              unit: "px",
              background: "pitch",
            },
            field: {
              surfaceType: "pitch",
              view: "half",
              orientation: "horizontal",
              zones: [
                {
                  zoneId: "zone_rondo",
                  shape: "rectangle",
                  x: 280,
                  y: 180,
                  width: 420,
                  height: 320,
                  label: "20x20 grid",
                },
              ],
            },
            objects: [
              {
                objectId: "cone_1",
                type: "cone",
                x: 280,
                y: 180,
                color: "#f97316",
              },
              {
                objectId: "cone_2",
                type: "cone",
                x: 700,
                y: 180,
                color: "#f97316",
              },
              {
                objectId: "cone_3",
                type: "cone",
                x: 280,
                y: 500,
                color: "#f97316",
              },
              {
                objectId: "cone_4",
                type: "cone",
                x: 700,
                y: 500,
                color: "#f97316",
              },
              {
                objectId: "player_a1",
                type: "player",
                x: 490,
                y: 200,
                team: "blue",
                role: "attacker",
                label: "A1",
              },
              {
                objectId: "player_a2",
                type: "player",
                x: 680,
                y: 340,
                team: "blue",
                role: "attacker",
                label: "A2",
              },
              {
                objectId: "player_a3",
                type: "player",
                x: 490,
                y: 480,
                team: "blue",
                role: "attacker",
                label: "A3",
              },
              {
                objectId: "player_a4",
                type: "player",
                x: 300,
                y: 340,
                team: "blue",
                role: "attacker",
                label: "A4",
                hasBall: true,
              },
              {
                objectId: "player_d1",
                type: "player",
                x: 430,
                y: 320,
                team: "red",
                role: "defender",
                label: "D1",
              },
              {
                objectId: "player_d2",
                type: "player",
                x: 560,
                y: 380,
                team: "red",
                role: "defender",
                label: "D2",
              },
              {
                objectId: "ball_1",
                type: "ball",
                x: 330,
                y: 340,
              },
            ],
            connections: [
              {
                connectionId: "conn_pass_1",
                type: "pass",
                fromRef: "player_a4",
                toRef: "player_a1",
                style: "solid-arrow",
                label: "press trigger",
              },
              {
                connectionId: "conn_move_1",
                type: "movement",
                fromRef: "player_d1",
                toRef: "player_a4",
                style: "curved-arrow",
              },
              {
                connectionId: "conn_support_1",
                type: "support",
                fromRef: "player_d2",
                toRef: "zone_rondo",
                style: "dashed-arrow",
              },
            ],
            annotations: [
              {
                annotationId: "ann_1",
                type: "text",
                x: 780,
                y: 220,
                text: "Defenders press and cover together",
              },
            ],
            legend: {
              show: true,
              items: [
                {
                  symbol: "blue",
                  meaning: "attacking players",
                },
                {
                  symbol: "red",
                  meaning: "defending players",
                },
              ],
            },
            renderHints: {
              showFieldStripes: true,
              preferLabels: true,
              theme: "classic-coaching-board",
            },
          },
        },
      ],
    },
    {
      activityId: "act_003",
      name: "5v5 + 2 Transition Game",
      phase: "game",
      minutes: 40,
      objective: "Transfer pressing cues into a directional game and attack quickly after the regain.",
      setup:
        "Use a half-field channel with one full goal and two mini goals. Play 5v5 in the main area with two neutral support players on the outside.",
      instructions:
        "Teams score on the full goal when building through the neutrals. If the defending team regains possession, they attack one of the two mini goals immediately.",
      organization:
        "Rotate neutral players every three minutes and coach from the side where pressing angles are easiest to see.",
      coachingPoints: [
        "recognize a bad touch as the pressing trigger",
        "win the ball with the next pass in mind",
        "recover compactly if the first press is beaten",
      ],
      progressions: ["limit the neutrals to one touch"],
      regressions: ["allow a free reset pass through the coach"],
      commonMistakes: [
        "front player presses without cover",
        "team wins the ball but plays backward immediately",
      ],
      equipment: ["10 cones", "2 mini goals", "1 full goal", "10 bibs", "2 balls"],
      space: {
        areaType: "half-field",
        sizeLabel: "half field channel",
      },
      constraints: ["coach serves the next ball in quickly to keep tempo high"],
    },
  ],
  cooldown: {
    minutes: 5,
    instructions: "Guide the group through light movement, breathing, and short partner stretching.",
    notes: "Finish with one quick reflection question about pressing cues.",
  },
  safetyNotes: [
    "reduce the grid if the surface becomes slippery",
    "manage defender work-to-rest if the weather is hot",
  ],
  successCriteria: [
    "players press with a clear first defender and second defender role",
    "the team looks forward quickly after regaining possession",
  ],
  assumptions: [
    "standard Club Vivo training equipment is available",
    "the coach has access to half a field for the main game",
  ],
  metadata: {
    generatedAt: "2026-04-03T18:30:00.000Z",
    generatedBy: "local-preview",
    generationMode: "mock",
    methodologyApplied: true,
    tenantScoped: false,
  },
};
